# Generated by Django 3.2 on 2025-02-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', through='api.RecipeTag', to='api.Tag'),
        ),
    ]
